### ISSUE TITLE
多个请求会造成阻塞

### ISSUE THREAD

**Issue by hansnow** [socrateslee/ynm3k#2]
### 配置文件
``` json
[
   ["/fast", "https://reqres.in/api/users?page=1"],
   ["/slow", "https://reqres.in/api/users?page=1&delay=10"]
]
```

### 重现步骤
1. 先请求`/fast`，马上可以得到响应；再请求`/slow`，10秒后得到响应。
2. 先请求`/slow`，再请求`/fast`，10秒后几乎同时得到两个请求的响应。

由此可见，`/fast`被`/slow`阻塞了

**Comment by socratescli** [comment]
默认启动ynm3k的服务器是python自带的wsgiref的simple_server，只有一个线程

现在增加--server参数，用来指定启动ynm3k的python web服务器，但是这个服务器的库比如先要安装过，比如首先

```
sudo pip install paste
```

然后启动ynm3k时加上 --server paste的选项。
